name: Autograding Tests
'on':
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    
    - name: Install dependencies
      run: npm install
    
    - name: Validate HTML
      run: npm run validate
    
    - name: Lab2Test
      id: lab2test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lab2Test
        command: npm test
        timeout: 5
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB2TEST_RESULTS: "${{steps.lab2test.outputs.result}}"
      with:
        runners: lab2test
